name: 'my first container action'
description: 'hands on lab'
author: 'Chun Ly'
input:
  myInput:
    description: 'greeting to use'
    required: true
    default: 'Awesome Guru'
outputs:
  myOutput:
    description: 'total memory'
runs:
  using: 'docker'
  image: 'Dockerfile'
  
